export const historyContainer:string =  "static mt-[135px] w-full px-12 md:p-24 text-2xl mt-16 overflow-y-scroll z-0 select-none ";
export const monthContainer:string =  "mb-12 border border-grey-100 ";
export const monthGrid:string =  "w-full h-full grid grid-cols-7 divide-x divide-y ";
export const monthHeader:string =  "col-span-1 border-b-2 border-red-500 flex justify-evenly items-center xl:text-4xl py-4 lg:pt-8 lg:pb-3 ";
export const weekHeaderContainer:string =  "w-full grid grid-cols-7 divide-x border-y border-grey-100 text-sm md:text-2xl ";
export const weekContainer:string =  "md:px-5 py-2 text-center ";
export const dayContainer:string =  "md:h-24 h-16 text-sm md:text-2xl px-5 py-2 cursor-pointer hover:shadow-xl md:flex ";
export const calenderIcons:string =  'mt-1 md:ml-4 lg:ml-7 md:text-[23px] text-red-500 ';
export const searchInputs:string =  ' ';
